# Generated by Django 4.0.1 on 2022-07-01 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20)),
                ('lastname', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(default='avatar.png', upload_to='avatar/')),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.BigIntegerField(blank=True)),
                ('avatar', models.ImageField(default='avatar.png', upload_to='avatars/')),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK')], max_length=5)),
                ('language', models.CharField(choices=[('English(US)', 'English(US)'), ('English(UK)', 'English(UK)')], max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
