# Generated by Django 4.0.1 on 2022-07-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK')], default='India', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('English(US)', 'English(US)'), ('English(UK)', 'English(UK)')], default='English(US)', max_length=11),
        ),
    ]
