# Generated by Django 4.0.1 on 2022-07-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0007_alter_profile_email_alter_profile_phone'),
        ('Post', '0004_alter_post_author_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='Profiles.Profile'),
        ),
    ]
