# Generated by Django 4.0.1 on 2022-07-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
