# Generated by Django 4.0.1 on 2023-06-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_post_liked_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='value',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
